Make the *-all upstart jobs idempotent.

diff --git a/ceph/templates/default/upstart-ceph-mon-all.conf.erb b/ceph/templates/default/upstart-ceph-mon-all.conf.erb
--- a/ceph/templates/default/upstart-ceph-mon-all.conf.erb
+++ b/ceph/templates/default/upstart-ceph-mon-all.conf.erb
@@ -10,7 +10,22 @@ script
   | while read f; do
     if [ -e "/srv/$f/done" ]; then
         id="${f##mon.}"
-    	start ceph-mon MON_ID="$id"
+
+	# upstart start(8) fails if the job is already running
+	# https://bugs.launchpad.net/upstart/+bug/878322
+	status ceph-mon MON_ID="$id" \
+	| {
+	  set -e
+	  read name goal_status rest
+	  case "$goal_status" in
+	    start/*)
+	      # no action needed
+	      ;;
+	    *)
+	      start ceph-mon MON_ID="$id"
+	      ;;
+	  esac
+	}
     fi
   done
 end script
diff --git a/ceph/templates/default/upstart-ceph-osd-all.conf.erb b/ceph/templates/default/upstart-ceph-osd-all.conf.erb
--- a/ceph/templates/default/upstart-ceph-osd-all.conf.erb
+++ b/ceph/templates/default/upstart-ceph-osd-all.conf.erb
@@ -9,7 +9,22 @@ script
   | while read f; do
     if [ -e "/srv/$f/done" ]; then
         id="${f##osd.}"
-    	start ceph-osd OSD_ID="$id"
+
+	# upstart start(8) fails if the job is already running
+	# https://bugs.launchpad.net/upstart/+bug/878322
+	status ceph-osd OSD_ID="$id" \
+	| {
+	  set -e
+	  read name goal_status rest
+	  case "$goal_status" in
+	    start/*)
+	      # no action needed
+	      ;;
+	    *)
+	      start ceph-osd OSD_ID="$id"
+	      ;;
+	  esac
+	}
     fi
   done
 end script
